name: pytorch_env
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.2.1
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.9.20
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tqdm=4.66.5
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - altair==5.5.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - imageio==2.36.0
      - imgaug==0.4.0
      - importlib-resources==6.4.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - multidict==6.1.0
      - narwhals==1.15.1
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pandas==2.2.3
      - propcache==0.2.1
      - protobuf==5.29.0
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - referencing==0.35.1
      - rich==13.9.4
      - rpds-py==0.21.0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - shapely==2.0.6
      - six==1.16.0
      - smmap==5.0.1
      - streamlit==1.40.2
      - sympy==1.13.1
      - tenacity==9.0.0
      - tifffile==2024.8.30
      - toml==0.10.2
      - torchaudio==2.5.1
      - torchmetrics==1.6.0
      - torchvision==0.20.1
      - tornado==6.4.2
      - tzdata==2024.2
      - ultralytics==8.3.49
      - ultralytics-thop==2.0.13
      - watchdog==6.0.0
      - yarl==1.18.3
      - zipp==3.21.0

